kind: Service
apiVersion: v1
metadata:
  name: filestorage-users
  labels:
    name: filestorage-users
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: filestorage-users
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestorage-users
spec:
  selector:
    matchLabels:
      app: filestorage-users
  replicas: 2
  template:
    metadata:
      labels:
        app: filestorage-users
    spec:
      containers:
        - name: filestorage-users
          image: localhost:5000/dev/filestorage-users
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials # Secret Name
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

